//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class JADWAL
    {
        public int ID { get; set; }
        public Nullable<int> ID_MAHASISWA { get; set; }
        public int ID_PENGAJAR { get; set; }
    
        public virtual MAHASISWA MAHASISWA { get; set; }
        public virtual PENGAJAR PENGAJAR { get; set; }
    }
}
