//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAHASISWA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAHASISWA()
        {
            this.JADWALs = new HashSet<JADWAL>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JADWAL> JADWALs { get; set; }
    }
}
